// This file generated by ngrestcg
// For more information, please visit: https://github.com/loentar/ngrest

#include "HelloWorld.h"

std::string HelloWorld::echo(const std::string& text)
{
    return "Hi, " + text;
}

