// This file generated by ngrestcg
// For more information, please visit: https://github.com/loentar/ngrest

#include "app.h"

std::string app::echo(const std::string& text)
{
    return "Hi, " + text;
}

